
export const FILE_NON_EXIST = 'FILE_NON_EXIST';
export const EMPTY_FOLDER = 'EMPTY_FOLDER';
export const OPEN_FAILED = 'OPEN_FAILED';
export const ONLINE_LOADING = 'ONLINE_LOADING';
export const SUBTITLE_OFFLINE = 'SUBTITLE_OFFLINE';
export const NOT_SUPPORTED_SUBTITLE = 'NOT_SUPPORTED_SUBTITLE';
export const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
export const SUBTITLE_UPLOAD = 'SUBTITLE_UPLOAD';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';
export const ADD_NO_VIDEO = 'ADD_NO_VIDEO';
