
export const FILE_NON_EXIST = 'FILE_NON_EXIST';
export const EMPTY_FOLDER = 'EMPTY_FOLDER';
export const OPEN_FAILED = 'OPEN_FAILED';
export const ONLINE_LOADING = 'ONLINE_LOADING';
export const NO_TRANSLATION_RESULT = 'NO_TRANSLATION_RESULT';
export const NOT_SUPPORTED_SUBTITLE = 'NOT_SUPPORTED_SUBTITLE';
