export const Video = {
  SRC_SET: 'SRC_SET',
  INITIALIZE: 'INITIALIZE',
  INCREASE_VOLUME: 'INCREASE_VOLUME',
  DECREASE_VOLUME: 'DECREASE_VOLUME',
  TOGGLE_MUTED: 'TOGGLE_MUTED',
  INCREASE_RATE: 'INCREASE_RATE',
  DECREASE_RATE: 'DECREASE_RATE',
  CHANGE_RATE: 'CHANGE_RATE',
  PLAY_VIDEO: 'PLAY_VIDEO',
  PAUSE_VIDEO: 'PAUSE_VIDEO',
  META_INFO: 'META_INFO',
  UPDATE_DELAY: 'UPDATE_DELAY',
  ADD_AUDIO_TRACK: 'ADD_AUDIO_TRACK',
  REMOVE_AUDIO_TRACK: 'REMOVE_AUDIO_TRACK',
  SWITCH_AUDIO_TRACK: 'SWITCH_AUDIO_TRACK',
  REMOVE_ALL_AUDIO_TRACK: 'REMOVE_ALL_AUDIO_TRACK',
  LOOP: 'LOOP',
};

export const Subtitle = {
  ADD_SUBTITLE_WHEN_LOADING: 'ADD_SUBTITLE_WHEN_LOADING',
  ADD_SUBTITLE_WHEN_READY: 'ADD_SUBTITLE_WHEN_READY',
  ADD_SUBTITLE_WHEN_FAILED: 'ADD_SUBTITLE_WHEN_FAILED',
  ADD_SUBTITLE_WHEN_LOADED: 'ADD_SUBTITLE_WHEN_LOADED',
  ADD_TO_VIDEO_SUBTITLE_MAP: 'ADD_TO_VIDEO_SUBTITLE_MAP',
  REMOVE_FROM_VIDEO_SUBTITLE_MAP: 'REMOVE_FROM_VIDEO_SUBTITLE_MAP',
  INITIALIZE_VIDEO_SUBTITLE_MAP: 'INITIALIZE_VIDEO_SUBTITLE_MAP',
  CHANGE_CURRENT_SUBTITLE: 'CHANGE_SUBTITLE',
  RESET_SUBTITLES: 'RESET_SUBTITLES',
  RESET_ONLINE_SUBTITLES: 'RESET_ONLINE_SUBTITLES',
  OFF_SUBTITLES: 'OFF_SUBTITLES',
  UPDATE_METAINFO: 'UPDATE_METAINFO',
};

export const Input = {
  MOUSEMOVE_UPDATE: 'MOUSEMOVE_UPDATE',
  MOUSEDOWN_UPDATE: 'MOUSEDOWN_UPDATE',
  MOUSEUP_UPDATE: 'MOUSEUP_UPDATE',
  KEYDOWN_UPDATE: 'KEYDOWN_UPDATE',
  KEYUP_UPDATE: 'KEYUP_UPDATE',
  WHEEL_UPDATE: 'WHEEL_UPDATE',
};
