export const Video = {
  INITIALIZE: 'INITIALIZE',
  INCREASE_VOLUME: 'INCREASE_VOLUME',
  DECREASE_VOLUME: 'DECREASE_VOLUME',
  INCREASE_RATE: 'INCREASE_RATE',
  DECREASE_RATE: 'DECREASE_RATE',
};

export const Subtitle = {
  ADD_SUBTITLE: 'ADD_SUBTITLE',
};
