export const Video = {
  SRC_SET: 'SRC_SET',
  INITIALIZE: 'INITIALIZE',
  INCREASE_VOLUME: 'INCREASE_VOLUME',
  DECREASE_VOLUME: 'DECREASE_VOLUME',
  TOGGLE_MUTED: 'TOGGLE_MUTED',
  INCREASE_RATE: 'INCREASE_RATE',
  DECREASE_RATE: 'DECREASE_RATE',
  PLAY_VIDEO: 'PLAY_VIDEO',
  PAUSE_VIDEO: 'PAUSE_VIDEO',
  META_INFO: 'META_INFO',
};

export const Subtitle = {
  ADD_SUBTITLE: 'ADD_SUBTITLE',
};
