export const Video = {
  // error state
  ERRORCODE_UPDATE: 'ERRORCODE_UPDATE',
  ERRORMESSAGE_UPDATE: 'ERRORMESSAGE_UPDATE',
  // network state
  SRC_UPDATE: 'SRC_UPDATE',
  CURRENTSRC_UPDATE: 'CURRENTSRC_UPDATE',
  NETWORKSTATE_UPDATE: 'NETWORKSTATE_UPDATE',
  BUFFERED_UPDATE: 'BUFFERED_UPDATE',
  CANPLAYTYPE_UPDATE: 'CANPLAYTYPE_UPDATE',
  CROSSORIGIN_UPDATE: 'CROSSORIGIN_UPDATE',
  PRELOAD_UPDATE: 'PRELOAD_UPDATE',
  // ready state
  READYSTATE_UPDATE: 'READYSTATE_UPDATE',
  SEEKING_UPDATE: 'SEEKING-UPDATE',
  // playback state
  DURATION_UPDATE: 'DURATION_UPDATE',
  PAUSED_UPDATE: 'PAUSED_UPDATE',
  ENDED_UPDATE: 'ENDED_UPDATE',
  PLAYED_UPDATE: 'PLAYED_UPDATE',
  SEEKABLE_UPDATE: 'SEEKABLE-UPDATE',
  CURRENTTIME_UPDATE: 'CURRENTTIME_UPDATE',
  DEFAULTPLAYBACK_UPDATE: 'DEFAULTPLAYBACKRATE_UPDATE',
  RATE_UPDATE: 'RATE_UPDATE',
  AUTOPLAY_UPDATE: 'AUTOPLAY_UPDATE',
  LOOP_UPDATE: 'LOOP',
  // controls
  CONTROLS_UPDATE: 'CONTROLS_UPDATE',
  VOLUME_UPDATE: 'VOLUME_UPDATE',
  MUTE_UPDATE: 'MUTE_UPDATE',
  DEFAULTMUTED_UPDATE: 'DEFAULTMUTED_UPDATE',
};

export const Subtitle = {
  ADD_SUBTITLE: 'ADD_SUBTITLE',
};
