export const Video = {
  VOLUME_UPDATE: 'VOLUME_UPDATE',
  TOGGLE_MUTE: 'TOGGLE_MUTE',
  MUTE_UPDATE: 'MUTE_UPDATE',
  RATE_UPDATE: 'RATE_UPDATE',
};

export const Subtitle = {
  ADD_SUBTITLE: 'ADD_SUBTITLE',
};
