/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/interface-name-prefix */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import Vue, { VNode } from 'vue'; // eslint-disable-line no-unused-vars

declare global {
  declare const __static: string; //eslint-disable-line
  interface Screen {
    availLeft: number;
    availTop: number;
  }
  namespace JSX {
    interface Element extends VNode {} //eslint-disable-line
    interface ElementClass extends Vue {} //eslint-disable-line
    interface IntrinsicElements {
      [elem: string]: unknown;
    }
  }

  type Optional<T> = { [key in keyof T]?: T[key] };
  interface JsonMap {
    [member: string]: string | number | boolean | null | JsonArray | JsonMap;
  }
  interface JsonArray extends Array<string | number | boolean | null | JsonArray | JsonMap> {} // eslint-disable-line
  type Json = JsonMap | JsonArray | string | number | boolean | null;

  interface AbortablePromise<T> extends Promise<T> {
    abort();
  }
}

declare module '*.vue' {
  export default Vue;
}

declare module 'vue/types/vue' {
  interface Vue {
    $store: any;
    $bus: Vue;
    $ga: any;
    $electron: Electron.RendererInterface;
  }
}

declare module 'electron' {
  enum AVSampleFormat {
    AV_SAMPLE_FMT_NONE = -1,
    /** unsigned 8bits */
    AV_SAMPLE_FMT_U8,
    /** signed 16 bits */
    AV_SAMPLE_FMT_S16,
    /** signed 32 bits */
    AV_SAMPLE_FMT_S32,
    /** float */
    AV_SAMPLE_FMT_FLT,
    /** double */
    AV_SAMPLE_FMT_DBL,
    /** unsigned 8 bits, planar */
    AV_SAMPLE_FMT_U8P,
    /** signed 16 bits, planar */
    AV_SAMPLE_FMT_S16P,
    /** signed 32 bits, planar */
    AV_SAMPLE_FMT_S32P,
    /** float, planar */
    AV_SAMPLE_FMT_FLTP,
    /** double, planar */
    AV_SAMPLE_FMT_DBLP,
    /** Number of sample formats. DO NOT USE if linking dynamically */
    AV_SAMPLE_FMT_NB,
  }
  interface SPlayerAPI {
    /** get media info of a media file */
    getMediaInfo(
      /** media file path */
      path: string,
      callback: (
        /** media info json string */
        info: string,
      ) => void,
    ): void;
    /** get a snapshot of a video file */
    snapshotVideo(
      /** source video path to snapshot from */
      srcVideoPath: string,
      /** image path to save */
      imagePath: string,
      /** time string in format of hh:mm:ss */
      time: string,
      /** width number in string */
      width: string,
      /** height number in string */
      height: string,
      callback: (
        /** if not '0', an error occurred */
        err: string,
      ) => void,
    ): void;
    /** extract subtitle fragment from a video file (@cliflix/electron@4.0.7-dev.1) */
    extractSubtitles(
      /** source video path to extract subtitle from */
      srcVideoPath: string,
      /** subtitle stream index to extract, if -1 will auto select the default track */
      streamIndex: number,
      /** position of the last subtitle extracted or seconds of the video */
      posOrSeconds: number,
      /** whether posOrSeconds param is seconds of the video */
      isSeconds: boolean,
      /** subtitle dialogues count */
      dialogueCount: number,
      callback: (
        /** if not '', an error occurred */
        error: string,
        /** video position of the last extracted dialogue */
        position: number,
        /** buffer of the extracted dialogues */
        data: Buffer | null,
      ) => void,
    ): void;
    /** stop the subtitle extraction */
    stopExtractSubtitles(): void;
    /** generate thumbnails in the order of left-to-right and top-to-bottom */
    generateThumbnails(
      /** source video path to extract thumbnails from */
      srcVideoPath: string,
      /** image path to save */
      imagePath: string,
      /** in seconds */
      interval: number,
      /** height will be generated by video ratio automatically */
      thumbnailWidth: string,
      columnThumbnailCount: string,
      /** auto calculated now, pass 0 */
      rowThumbnailCount: '0',
      callback: (
        /** if not '0', an error occurred */
        err: string,
      ) => void,
    ): void;
    /** extract audio raw data from a video */
    grabAudioFrame(
      /** source video path to grab audio frames from */
      srcVideoPath: string,
      /** only available when first sample a video */
      seekPosition: string,
      /** stream index string in the form of 0:s:0 */
      streamIndex: number,
      /** integer, usually in [1, 8], 0 for all tracks */
      trackIndex: number,
      /** integer, usually in [1, 8] */
      resampleTracksCount: number,
      /** usually in [11000, 48000] */
      resampleRate: number,
      resampleFormat: AVSampleFormat,
      /** usually in [1, 200] */
      frameCount: number,
      callback: (
        /** if not '0', an error occurred */
        err: string,
        frameBuffer?: Buffer,
        /**
         * a string joined by comma(,) with values of
         * - pts: can be used as @param seekPosition
         * - channels
         * - format: @enum AVSampleFormat
         * - nb_samples: sample count
         * - sample_rate
         */
        frameData: string,
      ) => void,
    ): void;
    /** stop last audio frame extraction to switch to another video/audio track */
    stopGrabAudioFrame(): void;
  }
  const splayerx: SPlayerAPI;

  interface IpcMain {
    on(channel: 'media-info-request', listener: (event: Event, path: string) => void): this;
    on(
      channel: 'snapshot-request',
      listener: (
        event: Event,
        videoPath: string,
        imagePath: string,
        timeString: string,
        width: number,
        height: number,
      ) => void,
    ): this;
    on(
      channel: 'subtitle-metadata-request',
      listener: (
        event: Event,
        videoPath: string,
        streamIndex: number,
        subtitlePath: string,
      ) => void,
    ): this;
    on(
      channel: 'subtitle-cache-request',
      listener: (event: Event, videoPath: string, streamIndex: number) => void,
    ): this;
    on(
      channel: 'subtitle-stream-request',
      listener: (event: Event, videoPath: string, streamIndex: number, time: number) => void,
    ): this;
    on(
      channel: 'subtitle-destroy-request',
      listener: (event: Event, videoPath: string, streamIndex: number) => void,
    ): this;
    on(
      channel: 'thumbnail-request',
      listener: (
        event: Event,
        videoPath: string,
        imagePath: string,
        thumbnailWidth: number,
        columnThumbnailCount: number,
        rowThumbnailCount: number,
      ) => void,
    ): this;
  }

  interface IpcRenderer {
    send(channel: 'media-info-request', path: string): void;
    send(
      channel: 'snapshot-request',
      videoPath: string,
      imagePath: string,
      timeString: string,
      width: number,
      height: number,
    ): void;
    send(
      channel: 'subtitle-metadata-request',
      videoPath: string,
      streamIndex: number,
      subtitlePath: string,
    ): this;
    send(channel: 'subtitle-cache-request', videoPath: string, streamIndex: number): this;
    send(
      channel: 'subtitle-stream-request',
      videoPath: string,
      streamIndex: number,
      time: number,
    ): this;
    send(channel: 'subtitle-destroy-request', videoPath: string, streamIndex: number): this;
    send(
      channel: 'thumbnail-request',
      videoPath: string,
      imagePath: string,
      thumbnailWidth: number,
      columnThumbnailCount: number,
      rowThumbnailCount: number,
    ): void;

    on(
      channel: 'media-info-reply',
      listener: (event: Event, error?: Error, info: string) => void,
    ): this;
    on(
      channel: 'snapshot-reply',
      listener: (event: Event, error?: Error, path: string) => void,
    ): this;
    on(
      channel: 'subtitle-metadata-reply',
      listener: (event: Event, error?: Error, finished: boolean, matadata?: string) => void,
    ): this;
    on(
      channel: 'subtitle-cache-reply',
      listener: (event: Event, error?: Error, finished: boolean, payload?: string) => void,
    ): this;
    on(
      channel: 'subtitle-stream-reply',
      listener: (event: Event, error?: Error, dialogue: string) => void,
    ): this;
    on(channel: 'subtitle-destroy-reply', listener: (event: Event, error?: Error) => void): this;
    on(
      channel: 'thumbnail-reply',
      listener: (event: Event, error?: Error, path: string) => void,
    ): this;

    once(
      channel: 'media-info-reply',
      listener: (event: Event, error?: Error, info: string) => void,
    ): this;
    once(
      channel: 'snapshot-reply',
      listener: (event: Event, error?: Error, path: string) => void,
    ): this;
    once(
      channel: 'subtitle-metadata-reply',
      listener: (event: Event, error?: Error, finished: boolean, matadata?: string) => void,
    ): this;
    once(
      channel: 'subtitle-cache-reply',
      listener: (event: Event, error?: Error, finished: boolean, payload?: string) => void,
    ): this;
    once(
      channel: 'subtitle-stream-reply',
      listener: (event: Event, error?: Error, dialogue: string) => void,
    ): this;
    once(channel: 'subtitle-destroy-reply', listener: (event: Event, error?: Error) => void): this;
    once(
      channel: 'thumbnail-reply',
      listener: (event: Event, error?: Error, path: string) => void,
    ): this;
  }

  interface Event {
    reply(channel: string, ...args: any[]): void;
    reply(channel: 'media-info-reply', error?: Error, info: string): void;
    reply(channel: 'snapshot-reply', error?: Error, path: string): this;
    reply(
      channel: 'subtitle-metadata-reply',
      error?: Error,
      finished: boolean,
      matadata: string,
    ): this;
    reply(channel: 'subtitle-cache-reply', error?: Error, finished: boolean): this;
    reply(channel: 'subtitle-stream-reply', error?: Error, dialogue: string): this;
    reply(channel: 'subtitle-destroy-reply', error?: Error): this;
    reply(channel: 'thumbnail-reply', error?: Error, path: string): void;
  }
}
