/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/interface-name-prefix */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import Vue, { VNode } from 'vue'; // eslint-disable-line no-unused-vars
import { AxiosInstance } from 'axios';

declare global {
  declare const __static: string; //eslint-disable-line
  interface Screen {
    availLeft: number;
    availTop: number;
  }
  namespace JSX {
    interface Element extends VNode {} //eslint-disable-line
    interface ElementClass extends Vue {} //eslint-disable-line
    interface IntrinsicElements {
      [elem: string]: unknown;
    }
  }

  interface JsonMap { [member: string]: string | number | boolean | null | JsonArray | JsonMap }
  interface JsonArray extends Array<string | number | boolean | null | JsonArray | JsonMap> {} // eslint-disable-line
  type Json = JsonMap | JsonArray | string | number | boolean | null;
}

declare module '*.vue' {
  export default Vue;
}

declare module 'vue/types/vue' {
  interface Vue {
    $store: any;
    $bus: Vue;
    $ga: any;
    $electron: Electron.RendererInterface;
    axios: AxiosInstance;
    $http: AxiosInstance;
  }

  namespace Vue {
    const axios: AxiosInstance;
  }
}

declare module 'electron' {
  enum AVSampleFormat {
    AV_SAMPLE_FMT_NONE = -1,
    /** unsigned 8bits */
    AV_SAMPLE_FMT_U8,
    /** signed 16 bits */
    AV_SAMPLE_FMT_S16,
    /** signed 32 bits */
    AV_SAMPLE_FMT_S32,
    /** float */
    AV_SAMPLE_FMT_FLT,
    /** double */
    AV_SAMPLE_FMT_DBL,
    /** unsigned 8 bits, planar */
    AV_SAMPLE_FMT_U8P,
    /** signed 16 bits, planar */
    AV_SAMPLE_FMT_S16P,
    /** signed 32 bits, planar */
    AV_SAMPLE_FMT_S32P,
    /** float, planar */
    AV_SAMPLE_FMT_FLTP,
    /** double, planar */
    AV_SAMPLE_FMT_DBLP,
    /** Number of sample formats. DO NOT USE if linking dynamically */
    AV_SAMPLE_FMT_NB,
  }
  interface SPlayerAPI {
    /** get media info of a media file */
    getMediaInfo(
      /** media file path */
      path: string,
      callback: (
        /** media info json string */
        info: string,
      ) => void,
    ): void;
    /** get a snapshot of a video file */
    snapshotVideo(
      /** source video path to snapshot from */
      srcVideoPath: string,
      /** image path to save */
      imagePath: string,
      /** time string in format of hh:mm:ss */
      time: string,
      /** width number in string */
      width: string,
      /** height number in string */
      height: string,
      callback: (
        /** if not '0', an error occurred */
        err: string,
      ) => void,
    ): void;
    /** extract one subtitle from a video file given stream index and format */
    extractSubtitles(
      /** source video path to extract subtitle from */
      srcVideoPath: string,
      /** subtitle path to save */
      subtitlePath: string,
      /** stream index string in the form of 0:s:0 */
      streamIndex?: string,
      callback: (
        /** if not '0', an error occurred */
        err: string,
      ) => void,
    ): void;
    /** generate thumbnails in the order of left-to-right and top-to-bottom */
    generateThumbnails(
      /** source video path to extract thumbnails from */
      srcVideoPath: string,
      /** image path to save */
      imagePath: string,
      /** height will be generated by video ratio automatically */
      thumbnailWidth: string,
      columnThumbnailCount: string,
      rowThumbnailCount: string,
      callback: (
        /** if not '0', an error occurred */
        err: string,
      ) => void,
    ): void;
    /** extract audio raw data from a video */
    grabAudioFrame(
      /** source video path to grab audio frames from */
      srcVideoPath: string,
      /** only available when first sample a video */
      seekPosition: string,
      /** stream index string in the form of 0:s:0 */
      streamIndex: number,
      /** integer, usually in [1, 8], 0 for all tracks */
      trackIndex: number,
      /** integer, usually in [1, 8] */
      resampleTracksCount: number,
      /** usually in [11000, 48000] */
      resampleRate: number,
      resampleFormat: AVSampleFormat,
      /** usually in [1, 200] */
      frameCount: number,
      callback: (
        /** if not '0', an error occurred */
        err: string,
        frameBuffer?: Buffer,
        /**
         * a string joined by comma(,) with values of
         * - pts: can be used as @param seekPosition
         * - channels
         * - format: @enum AVSampleFormat
         * - nb_samples: sample count
         * - sample_rate
         */
        frameData: string,
      ) => void,
    ): void;
    /** stop last audio frame extraction to switch to another video/audio track */
    stopGrabAudioFrame(): void;
  }
  const splayerx: SPlayerAPI;

  interface IpcMain {
    on(channel: 'media-info-request', listener: (event: Event, path: string) => void): this;
    on(channel: 'snapshot-request', listener: (event: Event,
      videoPath: string, imagePath: string,
      timeString: string,
      width: number, height: number,
    ) => void): this;
    on(channel: 'subtitle-request', listener: (event: Event,
      videoPath: string, subtitlePath: string,
      streamIndex: string,
    ) => void): this;
    on(channel: 'thumbnail-request', listener: (event: Event,
      videoPath: string, imagePath: string,
      thumbnailWidth: number,
      columnThumbnailCount: number, rowThumbnailCount: number,
    ) => void): this;
  }

  interface IpcRenderer {
    send(channel: 'media-info-request', path: string): void;
    send(channel: 'snapshot-request',
      videoPath: string, imagePath: string,
      timeString: string,
      width: number, height: number,
    ): void;
    send(channel: 'subtitle-request',
      videoPath: string, subtitlePath: string,
      streamIndex: string,
    ): void;
    send(channel: 'thumbnail-request',
      videoPath: string, imagePath: string,
      thumbnailWidth: number,
      columnThumbnailCount: number, rowThumbnailCount: number,
    ): void;

    on(channel: 'media-info-reply', listener: (event: Event, error?: Error, info: string) => void): this;
    on(channel: 'snapshot-reply', listener: (event: Event, error?: Error, path: string) => void): this;
    on(channel: 'subtitle-reply', listener: (event: Event, error: Error | undefined, path: string) => void): this;
    on(channel: 'thumbnail-reply', listener: (event: Event, error?: Error, path: string) => void): this;

    once(channel: 'media-info-reply', listener: (event: Event, error?: Error, info: string) => void): this;
    once(channel: 'snapshot-reply', listener: (event: Event, error?: Error, path: string) => void): this;
    once(channel: 'subtitle-reply', listener: (event: Event, error: Error | undefined, path: string) => void): this;
    once(channel: 'thumbnail-reply', listener: (event: Event, error?: Error, path: string) => void): this;
  }

  interface Event {
    reply(channel: string, ...args: any[]): void;
    reply(channel: 'media-info-reply', error?: Error, info: string): void;
    reply(channel: 'snapshot-reply', error?: Error, path: string): this;
    reply(channel: 'subtitle-reply', error: Error | undefined, path: string): this;
    reply(channel: 'thumbnail-reply', error?: Error, path: string): void;
  }
}
